# Generated by Django 3.0.3 on 2021-06-29 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TriviaApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='answers',
            new_name='first_answers',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='question',
            new_name='first_question',
        ),
        migrations.AddField(
            model_name='test',
            name='second_answers',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='second_question',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
