# Generated by Django 3.0.3 on 2021-06-30 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TriviaApp', '0004_auto_20210629_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='datetime',
            field=models.DateTimeField(max_length=100, null=True),
        ),
    ]
